### PR TITLE
Fix branch indicators in QTreeView/QTreeWidget

### PR DESCRIPTION
**Pull request by eblade**

### CODE REVIEW

**Comment by eblade** [comment]
Hi, ran into a little issue with the item branch indicators that wouldn't show in my QTreeWidget. Did a little tweaking of the qss and SVGs used along with adding i a sub item to the example. There are probably better qss ways to do this and maybe this wasn't the intended design, but this works; so if you want it.

Basically I fixed the filename types and scaled the svgs down by 2:1. Here are some shots of the example app:

image

image

image

image

**Comment by Alexhuszagh** [comment]
I'll take a look at this tomorrow, thank you.

**Comment by Alexhuszagh** [comment]
Thanks for this, I definitely need to do some work to optimize the look and feel, but this is a major step-up.

**Comment by Alexhuszagh** [comment]
I was able to fix the QTreeView to properly display the branch open and closed icons, as well as retain the branching-lines (and make them slightly nicer in general).

The new UI looks like this:

screenshot_20181219_175553
screenshot_20181219_175608

You helped me realize my mistake in a few places, which was huge to help render this properly. I mistook the border-image (which is for the branching lines, not icons) and image properties, and also had to do some careful hijinks to ensure the open and closed icons look good together (they actually have to be scaled to different sizes, since Qt does something weird in rendering them).

Let me know if there any issues, and, thank you so much.

**Comment by eblade** [comment]
Nice! That looks a lot better than the thing I did! 

Happy I could contribute a little.

**Pull request merged**
